### ISSUE TITLE
No Fan Speed Service Available

### ISSUE THREAD

**Issue by duczz** [hristo-atanasov/Tasmota-IRHVAC#151]
Hello,

it looks like there is no Fan Speed Service in homeassstiant available, can we add it?
Edit: I found it, it works with homeassistant internal commands, is that the way i should go or you wanna add the fan speed option?
```  
- service: climate.set_fan_mode
````
![image](https://github.com/user-attachments/assets/c8b04db5-3df1-4bfa-accb-59b8f51afd8c)

**Comment by scargill** [comment]
Is fan speed going to be fixed in this code? I'm not getting fan speeed control either..

**Comment by hristo-atanasov** [comment]
It is working fine. Just tested it.![Screenshot_2024-11-07-14-53-41-809_io.homeassistant.companion.android.jpg](https://github.com/user-attachments/assets/fbcf8371-7969-4dce-83c7-e5f1c183c60e)

**Comment by hristo-atanasov** [comment]
I see you're trying to "urge" the situation. I am not working at 911 or 112. I'm not policeman, firefighter or doctor. You can use this custom component "as is". It is your decision if you will use it or not. If you decide to use it - you're doing it on you own risk. I'm not responsible for any discomfort,  damages, financial losses etc. due to temporary malfunctioning of this component. I'll also not going to feel bad or sorry about it. Keep in mind, that initially this component was created to fit my needs and I decided to share it with the world. So I'm actively using it too. When something breaks I also want it working again ASAP. While not working I have the "opportunity" to use the original remote controll, that I believe is included in every AC package, completely for free. And it is very reliable too.
> Is fan speed going to be fixed in this code? I'm not getting fan speeed control either..

**Comment by hristo-atanasov** [comment]
> Hello,
> 
> it looks like there is no Fan Speed Service in homeassstiant available, can we add it?
> Edit: I found it, it works with homeassistant internal commands, is that the way i should go or you wanna add the fan speed option?
> ```  
> - service: climate.set_fan_mode
> ````
> ![image](https://github.com/user-attachments/assets/c8b04db5-3df1-4bfa-accb-59b8f51afd8c)
> 

This is how it will be untill Home Assistant developers change the name of the action/service. It is not magically working with HA internal commands - I wrote the code for this functionality and I named it the way that Home Assistant want me to name it, in order to work. I don't think it is necessary to rename it or add second service, with different name, that is doing the same.

**Comment by hristo-atanasov** [comment]
> Yeah but No tasmota_irhvac_fann_speed are existing.
> I fixed it also with the build in.
> 
> But would be great when im searching tasmota_irhvac and have all

This is a custom integration with custom name, but in the end it represents a HA climate device. So you have to search "climate" services.
