### ISSUE TITLE
Vane (swing) setting

### ISSUE THREAD

**Issue by itec78** [hristo-atanasov/Tasmota-IRHVAC#31]
Hi.
On my Mitsubishi conditioner I can change angle of the vane (fixed, no swing)
My model has only the vertical vane.
Looking at the mqtt values, I get these options:
"SwingV":"Highest","SwingH":"Middle"
"SwingV":"High","SwingH":"Middle"
"SwingV":"Middle","SwingH":"Middle"
"SwingV":"Low","SwingH":"Middle"
"SwingV":"Lowest","SwingH":"Middle"
"SwingV":"Auto","SwingH":"Middle"

How can I control vane?
BR
EC

**Comment by hristo-atanasov** [comment]
Currently it is not possible, because of limitation in Thermostat card in HA, that does not have such dropdown. May be it will be possible in feature releases of HA. In some of the future releases I'll introduce such service, that will allow this, and it will be possible to use it via switch or some king of button. For now - you can't control it.

**Comment by nao-pon** [comment]
Added set_swingv, set_swingh services in v2022.08.30. Also reverted the vane position on swing-off to its previous fixed position.

We can now control the vane's swing and position. 👍 

A blueprint for an automation that uses dropdown inputs and services can be found below.

- https://gist.github.com/nao-pon/0db4765bc35727e7c84434d405f9c0a6


![FireShot Capture 044 - 管理者パネル – Home Assistant - hypha duckdns org](https://user-images.githubusercontent.com/1412630/187568158-e556090c-bc3a-457b-a133-c45ff7e0cada.png)
![FireShot Capture 047 - 管理者パネル – Home Assistant - hypha duckdns org (1)](https://user-images.githubusercontent.com/1412630/187568166-58e26363-d25a-44e4-ac1e-fd3041f76e19.png)
