### ISSUE TITLE
Support for Tasmota 10.0.0

### ISSUE THREAD

**Issue by rishabmehta7** [hristo-atanasov/Tasmota-IRHVAC#49]
Tasmota no longer has a ircustom image after 9.3.1
Does this work on Tasmota 10.0.0 IR?

Rishab

**Comment by cociweb** [comment]
Tasmota-ir 10.0.0 has all of the IRRemoteESP8266 protocols are included: HVAC models as well. You can expect the same behaviour than the previous tasmota versions from this plugin pov.

**Comment by rishabmehta7** [comment]
So i have a sOnOff TH16 running tasmota-ir. I see the IR receive on console. But no updates happen on HA. 
Also any update HA doesn't trigger a IR Send :-(

**Comment by cociweb** [comment]
is your tasmota ever worked with 9.3.1 (or before) with your current HA config?
What does 'No updates' mean? HA does not get the mqtt messages and that's why it not get anything, or the mqtt statuses are ok, and only the integration/thermostat card does not interwork?

Is your mqtt server integrated under HA and is your mqtt server gets correctly the data from tasmota? (https://siytek.com/how-to-set-up-tasmota-mqtt-auto-discovery-for-home-assistant/)

**Comment by rishabmehta7** [comment]
No everything was working before as expected. I just made a stupid mistake of upgrading my Tasmota and that broke things for me.
MQTT is setup correctly
The internal Relay on TH16 is usable as a switch from HA, the Temperature and Humidity Sensor report the state properly.

**Comment by hristo-atanasov** [comment]
Just do as I do - use 8.1 .. One wise man once said - if it works, don't update it .. :)

**Comment by rishabmehta7** [comment]
The latest release is working!
