### ISSUE TITLE
[custom_components.tasmota_irhvac.climate] Unable to update from sensor: could not convert string to float: 'unknown'

### ISSUE THREAD

**Issue by DiggiD** [hristo-atanasov/Tasmota-IRHVAC#5]
keep getting this error in the logs..
not sure what its referring to

**Comment by conrad66** [comment]
I have the same problem
![Screenshot_12](https://user-images.githubusercontent.com/5843698/84486737-78d51300-aca6-11ea-9ef9-92dca3ce569d.png)

**Comment by hristo-atanasov** [comment]
Yes, soon I'll fix that. It happens when you don't have temp sensor, or your temp sensor is not initialized yet, and instead of returning float for temp (like for example 22.5), it just returns 'unknown' or 'N/A' .. When I have some time to change the code, I'll make it to check if it is a string, and if yes to return some default temperature. :) I hope even with this error in the log you can use the component. :)

**Comment by hristo-atanasov** [comment]
Ok, I change dthe code so it shows debugs instead of errors. You will see this message only if you set the logger to debug mode. :)
